#conexao banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/app_tracker
spring.datasource.username=postgres
spring.datasource.password=fealgo

#hibernate
#update pra atualizar automaticamente o banco de dados
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#mostra as queries no console
spring.jpa.show-sql=true